export const commentsTypes = {
  FETCH_ALL_COMMENTS: "FETCH_ALL_COMMENTS",
  ADD_NEW_COMMENT: "ADD_NEW_COMMENT ",
  GET_ALL_COMMENTS: "GET_ALL_COMMENTS",
  UPDATE_COMMENT_BY_ID: "UPDATE_COMMENT_BY_ID",
  DELETE_COMMENT_BY_ID: "DELETE_COMMENT_BY_ID",
  LOAD_USERS_LOADING: "LOAD_USERS_LOADING"
}