export const postsTypes = {
  FETCH_ALL_POSTS: "FETCH_ALL_POSTS",
  ADD_NEW_POST: "ADD_NEW_POST ",
  GET_ALL_COMMENTS: "GET_ALL_COMMENTS",
  UPDATE_COMMENT_BY_ID: "UPDATE_COMMENT_BY_ID",
  DELETE_COMMENT_BY_ID: "DELETE_COMMENT_BY_ID",
  LOAD_POSTS_LOADING: "LOAD_POSTS_LOADING"
}